id: mlops_demo_oss_dogs
owner: alexeynaiden
role: alexeynaiden/projects/mlops_demo_oss_dogs

defaults:
  preset: cpu-medium
  life_span: 1d
  env:
    BUCKET_NAME: mlops-oss-demo-dogs-s3
    CREDENTIALS: bucket-credentials-5e8a0de5-7384-4a5d-837a-40fc9040d5e2
    MLFLOW_TRACKING_URI: https://demo-oss-dogs-mlflow-server--$[[ project.owner ]].jobs.default.org.neu.ro
    PACHY_URI: pachyderm.green-hgx-2.org.neu.ro:30650
    PACHY_REPO: dogs-demo-s3
    NEURO_CLI_DISABLE_PYPI_VERSION_CHECK: true

volumes:
  remote_dataset:
    remote: storage:/$[[ project.owner ]]/$[[ flow.flow_id ]]/dataset
    mount: /dataset
  src:
    remote: storage:/$[[ project.owner ]]/$[[ flow.flow_id ]]/src
    mount: /usr/project/src
    local: src
  config:
    remote: storage:/$[[ project.owner ]]/$[[ flow.flow_id ]]/config
    mount: /usr/project/config
    local: config
  notebooks:
    remote: storage:/$[[ project.owner ]]/$[[ flow.flow_id ]]/notebooks
    mount: /usr/project/notebooks
    local: notebooks
  label_studio:
    remote: storage:/$[[ project.owner ]]/$[[ flow.flow_id ]]/label_studio
    mount: /usr/project/label_studio
    local: label_studio
  project:
    remote: storage:/$[[ project.owner ]]/$[[ flow.flow_id ]]/
    mount: /usr/project/
    local: .

images:
  train:
    ref: image:/$[[ project.owner ]]/$[[ flow.flow_id ]]/train:22.4.0
    dockerfile: $[[ flow.workspace ]]/Dockerfile
    context: $[[ flow.workspace ]]/
    build_preset: cpu-medium
  seldon:
    ref: image:/$[[ project.owner ]]/$[[ flow.flow_id ]]/seldon:22.4.0
    dockerfile: $[[ flow.workspace ]]/seldon/seldon.Dockerfile
    context: $[[ flow.workspace ]]/
    build_preset: cpu-medium
  label_studio:
    ref: image:/$[[ project.owner ]]/$[[ flow.flow_id ]]/label_studio:22.4.0
    dockerfile: $[[ flow.workspace ]]/label_studio/label_studio.Dockerfile
    context: $[[ flow.workspace ]]/label_studio
    build_preset: cpu-medium
