id: mlops_demo_oss_dogs
owner: alexeynaiden
role: alexeynaiden/projects/mlops_demo_oss_dogs

defaults:
  preset: cpu-small
  life_span: 1d
  env:
    PROJECT: /usr/project
    BUCKET_NAME: mlops-demo-oss-dogs
    CREDENTIALS: mlops-demo-oss-dogs-credentials
    MLFLOW_TRACKING_URI: https://demo-oss-dogs-mlflow-server--yevheniisemendiak.jobs.green-hgx-1.org.neu.ro
    PACHY_URI: pachyderm.green-hgx-2.org.neu.ro:30650
    PACHY_REPO: dogs-demo
    NEURO_CLI_DISABLE_PYPI_VERSION_CHECK: true

volumes:
  remote_dataset:
    remote: storage:/$[[ project.owner ]]/$[[ flow.flow_id ]]/dataset
    mount: /dataset
    local: remote_dataset
  src:
    remote: storage:/$[[ project.owner ]]/$[[ flow.flow_id ]]/src
    mount: /usr/project/src
    local: src
  config:
    remote: storage:/$[[ project.owner ]]/$[[ flow.flow_id ]]/config
    mount: /usr/project/config
    local: config
  notebooks:
    remote: storage:/$[[ project.owner ]]/$[[ flow.flow_id ]]/notebooks
    mount: /usr/project/notebooks
    local: notebooks
  label_studio:
    remote: storage:/$[[ project.owner ]]/$[[ flow.flow_id ]]/label_studio
    mount: /usr/project/label_studio
    local: label_studio
  project:
    remote: storage:/$[[ project.owner ]]/$[[ flow.flow_id ]]/
    mount: /usr/project/
    local: .

images:
  train:
    ref: image:/$[[ project.owner ]]/$[[ flow.flow_id ]]/train:22.4.0
    dockerfile: $[[ flow.workspace ]]/Dockerfile
    context: $[[ flow.workspace ]]/
    build_preset: cpu-medium
  seldon:
    ref: image:/$[[ project.owner ]]/$[[ flow.flow_id ]]/seldon:22.7.0
    dockerfile: $[[ flow.workspace ]]/seldon/seldon.Dockerfile
    context: $[[ flow.workspace ]]/
    build_preset: cpu-medium
  label_studio:
    ref: image:/$[[ project.owner ]]/$[[ flow.flow_id ]]/label_studio:22.4.0
    dockerfile: $[[ flow.workspace ]]/label_studio/label_studio.Dockerfile
    context: $[[ flow.workspace ]]/label_studio
    build_preset: cpu-medium
