kind: batch
title: demo-oss-dogs-batch
id: mlops_demo_oss_dogs

defaults:
  cache:
    strategy: none

params:
  train_image_ref: ~
  mlflow_storage: ~
  mlflow_uri: ~
  pachy_uri: ~
  project_git_repo: ~
  project_git_branch: ~

tasks:
  - id: train
    image: $[[ params.train_image_ref ]]
    preset: cpu-medium-p
    life_span: 10d
    volumes:
      - ${{ params.mlflow_storage }}:/usr/local/share/mlruns:rw
      - secret:gh-rsa:/root/.ssh/id-rsa
    env:
      EXPOSE_SSH: "yes"
      PYTHONPATH: /usr/project
      PROJECT: /usr/project
      PACHY_URI: ${{ params.pachy_uri }}
      PACHY_REPO: dogs-demo
      MLFLOW_TRACKING_URI: ${{ params.mlflow_uri }}
      PROJECT_GIT_REPO: ${{ params.project_git_repo }}
      PROJECT_GIT_BRANCH: ${{ params.project_git_branch }}
    bash: |
        echo "IdentityFile ~/.ssh/id-rsa" > ~/.ssh/config
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git clone -b ${PROJECT_GIT_BRANCH} ${PROJECT_GIT_REPO} ${PROJECT}
        
        # Init pachctl
        pachctl config update context default --pachd-address ${PACHY_URI}
        pachctl config set active-context default
        pachctl inspect repo ${PACHY_REPO} || pachctl create repo ${PACHY_REPO}
        
        # Pull dataset: 
        pachctl get file ${PACHY_REPO}@master:/data/ -r -o ${PROJECT}/data/ | tee
        ls -R ${PROJECT}/data

        python -u ${PROJECT}/src/train.py \
          --data_dir ${PROJECT}/data/Images \
          --data_description ${PROJECT}/data/result.json