kind: batch
title: demo-oss-dogs-batch
id: mlops_demo_oss_dogs

defaults:
  cache:
    strategy: none

params:
  mlflow_storage: ~
  mlflow_uri: ~

tasks:
  - id: train
    image: $[[ images.train.ref ]]
    preset: cpu-medium
    life_span: 10d
    volumes:
      - ${{ params.mlflow_storage }}:/usr/local/share/mlruns:rw
      - ${{ volumes.project.ref }}
    env:
      EXPOSE_SSH: "yes"
      PYTHONPATH: /usr/project
    bash: |
      # Init pachctl
      pachctl config update context default --pachd-address ${PACHY_URI}
      pachctl config set active-context default

      # Pull dataset:
      pachctl get file ${PACHY_REPO}@master:/data/ -r -o ${PROJECT}/data/ | tee

      ls -R ${{ volumes.project.mount }}/data

      python -u {{ volumes.project.mount }}/src/train.py \
        --data_dir {{ volumes.project.mount }}/data/Images \
        --data_description {{ volumes.project.mount }}/data/result.json